import jsPDF from "jspdf";
import html2canvas from "html2canvas";

type ExportOptions = {
  fileName?: string;
  scale?: number;
  orientation?: "p" | "l";
  marginBottom?: number;
  showPageNumber?: boolean;
  hideColumns?: number[];
  singlePage?: boolean;
};

export async function previewToPdf(elementId: string, options?: ExportOptions) {
  const {
    fileName = "document",
    scale = 2,
    orientation = "p",

    showPageNumber = true,
  } = options || {};

  const element = document.getElementById(elementId);
  if (!element) return;

  // ================= AUTO CLEAN UI FOR PDF =================
  const hiddenElements: HTMLElement[] = [];

  // hide buttons, icons, clickable elements
  element.querySelectorAll("button, svg, [role='button']").forEach((el) => {
    const html = el as HTMLElement;
    hiddenElements.push(html);
    html.style.display = "none";
  });

  // hide mui accordion content
  element.querySelectorAll(".MuiCollapse-root").forEach((el) => {
    const html = el as HTMLElement;
    hiddenElements.push(html);
    html.style.display = "none";
  });

  // hide expand / checkbox column
  element.querySelectorAll(".MuiTableCell-paddingCheckbox").forEach((el) => {
    const html = el as HTMLElement;
    hiddenElements.push(html);
    html.style.display = "none";
  });

  // // hide empty & actions columns automatically
  // const table = element.querySelector("table");
  // if (table) {
  //   const headers = Array.from(table.querySelectorAll("th"));

  //   headers.forEach((th, index) => {
  //     const text = th.textContent?.trim().toLowerCase();

  //     if (!text || text === "actions") {
  //       (th as HTMLElement).style.display = "none";

  //       table.querySelectorAll("tr").forEach(tr => {
  //         const cell = tr.children[index] as HTMLElement;
  //         if (cell) cell.style.display = "none";
  //       });
  //     }
  //   });
  // }
  // hide selected columns dynamically
  if (options?.hideColumns?.length) {
    const table = element.querySelector("table");

    if (table) {
      options.hideColumns.forEach((colIndex) => {
        // header
        const th = table.querySelectorAll("th")[colIndex] as HTMLElement;
        if (th) {
          hiddenElements.push(th);
          th.style.display = "none";
        }

        // body
        table.querySelectorAll("tr").forEach((tr) => {
          const cell = tr.children[colIndex] as HTMLElement;
          if (cell) {
            hiddenElements.push(cell);
            cell.style.display = "none";
          }
        });
      });
    }
  }

  // A4 width  //
  const originalWidth = element.style.width;
  element.style.width = "794px";

  await new Promise((r) => setTimeout(r, 200));

  //Convert HTML to  Canvas//

  const canvas = await html2canvas(element, {
    scale,
    backgroundColor: "#ffffff",
    useCORS: true,
  });

  // ================= SINGLE ROW PDF MODE =================
  if (options?.singlePage) {
    const pdf = new jsPDF(orientation, "mm", "a4");

    const pageWidth = orientation === "p" ? 210 : 297;
    const pageHeight = orientation === "p" ? 295 : 200;

    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const y = Math.max(15, (pageHeight - imgHeight) / 2);

    pdf.addImage(
      canvas.toDataURL("image/png"),
      "PNG",
      10,
      y,
      imgWidth,
      imgHeight,
    );

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.text("Company Details", pageWidth / 2, 10, { align: "center" });
    pdf.line(10, 14, pageWidth - 10, 14);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(120);
    pdf.text("Generated by System", 10, pageHeight - 8);

    // ⭐ restore UI BEFORE returning
    hiddenElements.forEach((el) => (el.style.display = ""));
    element.style.width = originalWidth;

    pdf.save(`${fileName}.pdf`);
    return;
  }

  // restore UI after capture
  hiddenElements.forEach((el) => (el.style.display = ""));

  element.style.width = originalWidth;

  // A4 PDF Setup//

  const pdf = new jsPDF(orientation, "mm", "a4");

  //Page size calculation//

  const pageWidth = orientation === "p" ? 210 : 297;
  const pageHeight = orientation === "p" ? 295 : 200;

  const headerHeight = 18; // mm
  const footerHeight = 18; // mm
  const printableHeight = pageHeight - headerHeight - footerHeight;

  const imgWidth = pageWidth;

  const pageCanvas = document.createElement("canvas");
  const pageCtx = pageCanvas.getContext("2d");

  // convert printable area mm → pixels correctly
  const pxPerMm = canvas.width / pageWidth;
  const pxPageHeight = Math.floor(printableHeight * pxPerMm);

  let renderedHeight = 0;
  let pageNumber = 0;

  // Split pages  //

  while (renderedHeight < canvas.height) {
    pageCanvas.width = canvas.width;
    pageCanvas.height = Math.min(pxPageHeight, canvas.height - renderedHeight);

    pageCtx!.drawImage(
      canvas,
      0,
      renderedHeight,
      canvas.width,
      pageCanvas.height,
      0,
      0,
      canvas.width,
      pageCanvas.height,
    );

    const imgData = pageCanvas.toDataURL("image/png");

    if (pageNumber > 0) pdf.addPage();

    const pageImgHeight = (pageCanvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, headerHeight, imgWidth, pageImgHeight);

    renderedHeight += pageCanvas.height;
    pageNumber++;
  }

  // Page Numbers //

  // if (showPageNumber) {
  //   const pageCount = pdf.getNumberOfPages();

  //   for (let i = 1; i <= pageCount; i++) {
  //     pdf.setPage(i);

  //     pdf.setFont("helvetica", "normal");
  //     pdf.setFontSize(10);
  //     pdf.setTextColor(120);

  //     pdf.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - marginBottom, {
  //       align: "center",
  //     });
  //   }
  // }

  const pageCount = pdf.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);

    // HEADER
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.setTextColor(40);
    pdf.text("Company Report", pageWidth / 2, 10, { align: "center" });
    pdf.line(10, 14, pageWidth - 10, 14);

    // FOOTER
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(120);
    pdf.text("Generated by System", 10, pageHeight - 8);

    // PAGE NUMBER
    if (showPageNumber) {
      pdf.text(`Page ${i} of ${pageCount}`, pageWidth - 10, pageHeight - 8, {
        align: "right",
      });
    }
  }

  pdf.save(`${fileName}.pdf`);
}
